# Generated by Django 4.0.3 on 2022-03-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile.png', upload_to='profile/'),
        ),
    ]
