# Generated by Django 4.0.3 on 2022-03-18 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
    ]
