# Generated by Django 4.0.3 on 2022-03-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Size', 'size'), ('Color', 'color')], max_length=200, null=True),
        ),
    ]
