# Generated by Django 4.0.3 on 2022-03-30 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favourite',
            field=models.ManyToManyField(blank=True, null=True, related_name='fa_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
