# Generated by Django 4.0.3 on 2022-03-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_product_favourite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
