# Generated by Django 4.0.3 on 2022-12-08 09:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Specifications',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
